version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  install-packages:
    executor:
      name: node/default
      tag: 18.12.0
    working_directory: ~/rcr
    steps:
      - attach_workspace:
          at: ~/rcr
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: ~/rcr
          paths:
            - "."

  lint:
    executor:
      name: node/default
      tag: 18.12.0
    working_directory: ~/rcr
    steps:
      - attach_workspace:
          at: ~/rcr
      - run:
          name: Lint
          command: yarn lint

  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/rcr
    steps:
      - attach_workspace:
          at: ~/rcr
      - run:
          name: Build and publish package
          command: |
            VERSION_TAG=${CIRCLE_TAG/v/''}

            echo $VERSION_TAG

  # deploy:
  #   machine:
  #     image: ubuntu-2204:current
  #   steps:
  #     - run:
  #         name: Trigger webhook
  #         command: curl $DEPLOY_HOOK_URL


workflows:
  check:
    jobs:
      - install-packages:
          name: install packages
      - lint:
          requires:
            - install packages
      - build:
          requires:
            - lint

  deploy:
    jobs:
      - install-packages:
          name: install packages
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      - lint:
          requires:
            - install packages
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - lint
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         only:
      #           - /^v.*/
      #       branches:
      #         ignore: /.*/
     