version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  install-packages:
    executor:
      name: node/default
      tag: 18.12.0
    working_directory: ~/rcr
    steps:
      - attach_workspace:
          at: ~/rcr
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: ~/rcr
          paths:
            - "."

  lint:
    executor:
      name: node/default
      tag: 18.12.0
    working_directory: ~/rcr
    steps:
      - attach_workspace:
          at: ~/rcr
      - run:
          name: Lint
          command: yarn lint

  test:
    executor:
      name: node/default
      tag: 18.12.0
    working_directory: ~/rcr
    steps:
      - attach_workspace:
          at: ~/rcr
      - run:
          name: Unit test
          command: yarn test

  build-publish:
    executor:
      name: node/default
      tag: 18.12.0
    working_directory: ~/rcr
    steps:
      - attach_workspace:
          at: ~/rcr
      - run:
          name: Build and publish package
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" > ~/.npmrc
            yarn publish --non-interactive --access public

workflows:
  check:
    jobs:
      - install-packages:
          name: install packages
      - lint:
          requires:
            - install packages
      - test:
          requires:
            - install packages

  publish:
    jobs:
      - install-packages:
          name: install packages
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      - lint:
          requires:
            - install packages
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      - test:
          requires:
            - install packages
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      - build-publish:
          requires:
            - lint
            - test
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/